"""The ``upbox.audit.v1`` export format.

Newline-delimited JSON: exactly one ``header`` object, then one ``record`` per
captured request, then exactly one ``footer``. Self-describing and versioned, so
a file found on disk in two years still says what it is and what it covers.

Why not call this an "Article 26 export". Article 26(6) of the AI Act obliges a
deployer to keep "logs automatically generated by that high-risk AI system to
the extent such logs are under their control". Those are the provider-designed
logs contemplated by Article 12, emitted by the system itself. upbox observes
the network from outside the system, so its records corroborate such logs but
are not them, and no amount of formatting changes that. Separately, Regulation
(EU) 2026/1744 deferred those deployer obligations to 2 December 2027 for
Annex III systems. The header says all of this in the file itself rather than
leaving it to a README nobody exports.

The header carries the ruleset digests, without which an export cannot be
reproduced or defended: "which redaction rules were live on 12 July" otherwise
has no answer. It also carries the chain verification result and an explicit
coverage statement, because an audit record that silently omits traffic reads as
exhaustive when it is not.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from datetime import UTC, datetime
from importlib import resources
from pathlib import Path
from typing import IO, Any

from upbox import __version__
from upbox.addons import enforce, fingerprint, redact
from upbox.db import chain
from upbox.db.store import Store

SCHEMA = "upbox.audit.v1"

RECORD_FIELDS = (
    "seq",
    "ts",
    "tool",
    "method",
    "scheme",
    "host",
    "path",
    "req_bytes",
    "resp_bytes",
    "status",
    "headers_json",
    "body_excerpt",
    "body_hash",
    "redactions_applied_json",
    "enforcement",
)

COVERAGE_NOTE = (
    "upbox records only traffic that passed through its proxy from a process it "
    "was configured to capture, on a device with its CA installed. Certificate-pinned "
    "clients, non-proxied processes, traffic on other devices, and protocols upbox does "
    "not proxy are absent from this file. Absence of a record is not evidence that no "
    "request was made."
)

DISCLAIMER = (
    "Deployer-side network observation of AI tool traffic. These are NOT the logs "
    "automatically generated by a high-risk AI system within the meaning of Article 26(6) "
    "of Regulation (EU) 2024/1689, which concerns logs the system itself emits. "
    "Regulation (EU) 2026/1744 deferred those deployer obligations to 2 December 2027 "
    "(Annex III) and 2 August 2028 (Annex I)."
)

TIMESTAMP_NOTE = (
    "Capture-host wall clock at the time the response was recorded. Not attested by any "
    "time authority. The hash chain proves order, not time."
)

BODY_HASH_NOTE = (
    "SHA-256 of the full request body as forwarded, after redaction. Not the body as the "
    "tool originally composed it."
)


@dataclass(frozen=True)
class RulesetDigests:
    """SHA-256 of each rule file as it stood at export time."""

    tools: str
    redact: str
    allowlist: str

    def as_dict(self) -> dict[str, str]:
        return {
            "tools_sha256": self.tools,
            "redact_sha256": self.redact,
            "allowlist_sha256": self.allowlist,
        }


def ruleset_digests() -> RulesetDigests:
    """Digest the live rule files, falling back to the bundled defaults."""
    return RulesetDigests(
        tools=_digest_rule_file(fingerprint.USER_RULES_PATH, fingerprint.DEFAULT_RULES_RESOURCE),
        redact=_digest_rule_file(redact.USER_RULES_PATH, redact.DEFAULT_RULES_RESOURCE),
        allowlist=_digest_rule_file(enforce.USER_RULES_PATH, enforce.DEFAULT_RULES_RESOURCE),
    )


def _digest_rule_file(user_path: Path, bundled_resource: str) -> str:
    try:
        if user_path.exists():
            raw = user_path.read_bytes()
        else:
            raw = resources.files("upbox.rules").joinpath(bundled_resource).read_bytes()
    except OSError:
        return "unavailable"
    return hashlib.sha256(raw).hexdigest()


def write_audit_v1(
    store: Store,
    out: IO[str],
    *,
    since: str | None = None,
    until: str | None = None,
    tool: str | None = None,
) -> int:
    """Write an ``upbox.audit.v1`` stream. Returns the record count.

    The chain is verified before anything is written, so the header states an
    outcome that was actually checked rather than asserting integrity by
    formatting.
    """
    verification = store.verify_chain()
    rows = store.query_filtered(since=since, until=until, tool=tool)

    seqs = [int(row["seq"]) for row in rows if row["seq"] is not None]
    header = {
        "type": "upbox.audit.header",
        "schema": SCHEMA,
        "generated_at": datetime.now(UTC).isoformat(),
        "generator": {"name": "upbox", "version": __version__},
        "ruleset": ruleset_digests().as_dict(),
        "range": {"since": since, "until": until},
        "filters": {"tool": tool},
        "record_count": len(rows),
        "chain": {
            "algorithm": chain.CHAIN_ALGORITHM,
            "verification": verification.status,
            "head_hash": verification.head_hash,
            "first_seq_in_file": min(seqs) if seqs else None,
            "last_seq_in_file": max(seqs) if seqs else None,
            "entries_verified": verification.checked,
            "entries_deleted_by_retention": verification.entries_deleted,
            "content_cleared_by_retention": verification.content_unavailable,
            "rows_predating_the_chain": verification.unchained,
            "broken_at_seq": verification.broken_at,
            "detail": verification.detail,
        },
        "field_notes": {"ts": TIMESTAMP_NOTE, "body_hash": BODY_HASH_NOTE},
        "coverage": COVERAGE_NOTE,
        "disclaimer": DISCLAIMER,
    }
    _write_object(out, header)

    for row in rows:
        _write_object(out, _record(row))

    _write_object(
        out,
        {
            "type": "upbox.audit.footer",
            "record_count": len(rows),
            "head_hash": verification.head_hash,
            "note": "Verify the database this came from with: upbox verify",
        },
    )
    return len(rows)


def _record(row: Any) -> dict[str, Any]:
    record: dict[str, Any] = {"type": "upbox.audit.record"}
    for name in RECORD_FIELDS:
        record[name] = row[name]

    # Truncation is stated, not left for the reader to infer from a length.
    req_bytes = row["req_bytes"]
    excerpt = row["body_excerpt"]
    record["body_truncated"] = bool(
        req_bytes is not None and excerpt is not None and req_bytes > len(excerpt.encode("utf-8"))
    )
    record["redactions"] = json.loads(row["redactions_applied_json"] or "null")
    # 'flagged' reached the cloud. A reader scanning a column of statuses will
    # assume otherwise unless it is spelled out per record.
    record["enforcement_meaning"] = _enforcement_meaning(row["enforcement"])
    record["retention"] = {
        "pruned_at": row["pruned_at"],
        "pruned_fields": json.loads(row["pruned_fields"] or "null"),
        "legal_hold": bool(row["legal_hold"]),
    }
    record["chain"] = {
        "prev_hash": row["prev_hash"],
        "entry_hash": row["entry_hash"],
        "headers_sha256": row["headers_sha256"],
        "body_excerpt_sha256": row["body_excerpt_sha256"],
        "chained": row["seq"] is not None,
    }
    return record


def _enforcement_meaning(enforcement: str | None) -> str:
    if enforcement == "blocked":
        return (
            "off-allowlist, short-circuited with a 403; the request did not reach the destination"
        )
    if enforcement == "flagged":
        return "off-allowlist, forwarded to the destination anyway"
    return "on-allowlist, or no allowlist policy applied"


def _write_object(out: IO[str], obj: dict[str, Any]) -> None:
    json.dump(obj, out, ensure_ascii=False)
    out.write("\n")
